# Generated by Django 3.0 on 2019-12-13 11:01

from django.db import migrations, models
import ibanpy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyIBANModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_iban', ibanpy.models.MyIBANField()),
            ],
        ),
    ]
