# Generated by Django 3.0 on 2019-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresspy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='street_address',
            field=models.TextField(null=True),
        ),
    ]
