# Generated by Django 3.0 on 2019-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresspy', '0002_auto_20191213_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
